/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 chair.gltf --transform
Author: j.a.m (https://sketchfab.com/j.a.m)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-chair-41973aa1808d4a13b84c24497fc77c63
Title: Office Chair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/chair-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-21.91, 2.3, -108.05]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cylinder01_Matteplastic_0.geometry} material={materials.Matteplastic} />
        <mesh geometry={nodes.Cylinder01_BlackMetal_0.geometry} material={materials.BlackMetal} />
      </group>
      <group position={[-51.39, 55.29, -133.69]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Box02_Lether_0.geometry} material={materials.Lether} />
        <mesh geometry={nodes.Box02_Chairback_0.geometry} material={materials.Chairback} />
      </group>
      <group position={[-21.91, -0.06, -108.05]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-9.74, 28.28, -4.17]}>
          <mesh geometry={nodes.Cylinder04_Matteplastic_0.geometry} material={materials.Matteplastic} />
          <mesh geometry={nodes.Cylinder02_Matteplastic_0.geometry} material={materials.Matteplastic} position={[-1.58, 0.25, -4.73]} />
        </group>
        <group position={[23.84, 17.93, -4.17]}>
          <mesh geometry={nodes.Cylinder20_Matteplastic_0.geometry} material={materials.Matteplastic} />
          <mesh geometry={nodes.Cylinder19_Matteplastic_0.geometry} material={materials.Matteplastic} position={[-0.42, 1.54, -4.73]} />
        </group>
        <group position={[24.42, -17.13, -4.17]}>
          <mesh geometry={nodes.Cylinder21_Matteplastic_0.geometry} material={materials.Matteplastic} />
          <mesh geometry={nodes.Cylinder22_Matteplastic_0.geometry} material={materials.Matteplastic} position={[0.92, 1.31, -4.73]} />
        </group>
        <group position={[-8.75, -28.45, -4.17]}>
          <mesh geometry={nodes.Cylinder23_Matteplastic_0.geometry} material={materials.Matteplastic} />
          <mesh geometry={nodes.Cylinder24_Matteplastic_0.geometry} material={materials.Matteplastic} position={[1.58, -0.22, -4.73]} />
        </group>
        <group position={[-29.85, -0.52, -4.17]}>
          <mesh geometry={nodes.Cylinder26_Matteplastic_0.geometry} material={materials.Matteplastic} />
          <mesh geometry={nodes.Cylinder25_Matteplastic_0.geometry} material={materials.Matteplastic} position={[-0.7, 1.43, -4.73]} />
        </group>
        <mesh geometry={nodes.Rectangle02_Chrome_0.geometry} material={materials.Chrome} />
      </group>
      <mesh geometry={nodes.Rectangle11_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-16.04, 30.48, -108.05]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Line01_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-25.15, 24.27, -108.05]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder03_Matteplastic_0.geometry} material={materials.Matteplastic} position={[-14.46, 23.8, -108.05]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Line02_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-25.59, 24.17, -86.28]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Circle01_Matteplastic_0.geometry} material={materials.Matteplastic} position={[-29.26, 24.56, -81.48]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder07_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-18.74, 27.15, -126.39]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder08_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-12.85, 27.39, -126.4]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder09_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-12.9, 28.29, -131.49]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder10_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-18.79, 28.05, -131.48]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder11_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-18.78, 27.84, -84.72]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder12_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-18.73, 26.94, -89.81]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder13_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-12.89, 28.09, -84.71]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder14_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-12.84, 27.18, -89.8]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Line04_Matteplastic_0.geometry} material={materials.Matteplastic} position={[-18.11, 48.52, -79.05]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder15_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-19.86, 33.51, -79.26]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder16_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-12.68, 33.81, -79.2]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Line05_Matteplastic_0.geometry} material={materials.Matteplastic} position={[-18.11, 48.52, -136.57]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder17_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-12.68, 33.81, -136.43]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder18_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-19.86, 33.51, -136.36]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Box01_Lether_0.geometry} material={materials.Lether} position={[7.49, 34.37, -108.05]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/chair-transformed.glb')
