/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 web.gltf --transform
Author: peewee.id (https://sketchfab.com/p2eweeworld)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flat-design-web-b12df26ec16749d1abb589cceac9d1d1
Title: Flat Design WEB
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/web-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.95, 0, 0.59]} scale={[2.95, 0.07, 1]}>
          <mesh geometry={nodes.Cube_0.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.016']} />
        </group>
        <group position={[0.77, -0.02, 0.51]} scale={[0.94, 0.07, 0.44]}>
          <mesh geometry={nodes.Cube002_0.geometry} material={materials['Material.018']} />
          <mesh geometry={nodes.Cube002_1.geometry} material={materials['Material.014']} />
        </group>
        <group position={[0.33, 1.15, -0.3]} scale={[2.96, 0.12, 1.85]}>
          <mesh geometry={nodes.Cube006_0.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Cube006_1.geometry} material={materials['Material.006']} />
        </group>
        <group position={[0.36, 1.15, -2.01]} rotation={[0.04, 0, 0]} scale={[2.84, 1.58, 0.17]}>
          <mesh geometry={nodes.Cube007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube007_1.geometry} material={materials['Material.010']} />
        </group>
        <group position={[3.27, 1.15, 2.81]} rotation={[Math.PI / 2, 0, 0]} scale={[0.56, 0.56, 0.12]}>
          <mesh geometry={nodes.Cylinder003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Material.004']} />
        </group>
        <group position={[1.79, 1.15, 3.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.41, 0.41, 0.09]}>
          <mesh geometry={nodes.Cylinder004_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['Material.004']} />
        </group>
        <mesh geometry={nodes.Cube001_0.geometry} material={materials['Material.012']} position={[-1.94, -0.02, 0.26]} scale={[1.52, 0.07, 0.69]} />
        <mesh geometry={nodes.Cube003_0.geometry} material={materials['Material.012']} position={[0.77, -0.02, -0.6]} scale={[0.94, 0.07, 0.44]} />
        <mesh geometry={nodes.Cube004_0.geometry} material={materials['Material.010']} position={[0.3, -0.09, 0.5]} scale={[0.26, 0.03, 0.26]} />
        <mesh geometry={nodes.Cylinder_0.geometry} material={materials['Material.019']} position={[-3.63, -0.07, 1.87]} rotation={[Math.PI / 2, 0, 0]} scale={[0.11, 0.11, 0.06]} />
        <mesh geometry={nodes.Cylinder001_0.geometry} material={materials['Material.017']} position={[-3.31, -0.07, 1.87]} rotation={[Math.PI / 2, 0, 0]} scale={[0.11, 0.11, 0.06]} />
        <mesh geometry={nodes.Cylinder002_0.geometry} material={materials['Material.018']} position={[-3.01, -0.07, 1.87]} rotation={[Math.PI / 2, 0, 0]} scale={[0.11, 0.11, 0.06]} />
        <mesh geometry={nodes.Cube005_0.geometry} material={materials['Material.010']} position={[-0.47, -0.06, 1.85]} scale={[2.28, 0.05, 0.1]} />
        <mesh geometry={nodes.Cube008_0.geometry} material={materials['Material.010']} position={[3.11, -0.34, -1.02]} scale={[0.83, 0.05, 1.09]} />
        <mesh geometry={nodes.Cube009_0.geometry} material={materials['Material.009']} position={[3.11, -0.34, 0.15]} scale={[0.91, 0.08, 0.08]} />
        <mesh geometry={nodes.Cube010_0.geometry} material={materials['Material.011']} position={[3.12, -0.39, -0.32]} scale={[0.59, 0.02, 0.05]} />
        <mesh geometry={nodes.Cube014_0.geometry} material={materials['Material.002']} position={[-3.28, 1.02, 2.3]} scale={[0.03, 0.04, 0.76]} />
        <mesh geometry={nodes.Cube013_0.geometry} material={materials['Material.020']} position={[0.8, -0.03, 1.32]} rotation={[-Math.PI, 0, 0]} scale={[-0.6, 0.05, 0.07]} />
        <mesh geometry={nodes.Cube016_0.geometry} material={materials['Material.020']} position={[-2.33, -0.03, -0.66]} rotation={[-Math.PI, 0, 0]} scale={[-1.14, 0.05, 0.06]} />
        <mesh geometry={nodes.Mball008_0.geometry} material={materials['Material.024']} position={[-2.58, 1.15, 3.07]} scale={0.36} />
      </group>
    </group>
  )
}

useGLTF.preload('/web-transformed.glb')
